name: Deploy map to prod
on: [workflow_dispatch]
jobs:
  deploy_prod:
    if: github.repository_owner == 'ParkingReformNetwork'
    runs-on: ubuntu-latest
    steps:
      - name: Copy from staging to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRN_SERVER_HOST }}
          username: ${{ secrets.PRN_SERVER_USERNAME }}
          key: ${{ secrets.PRN_SERVER_PRIVATE_KEY }}
          script: |
            rsync --archive --verbose --compress --delete \
              /var/www/${{ secrets.PRN_SERVER_HOST }}/mandates-map-staging/ \
              /var/www/${{ secrets.PRN_SERVER_HOST }}/mandates-map/
